language: python
python:
  - 3.6
env:
  - BUILD_TYPE="Release"
  
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran liblapack-pic liblapack-dev
  - pip install netCDF4
  - pip install xarray
  - pip install scipy
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - git submodule init
  - git submodule update -j 6
  - rm -rf geoclaw
  - ln -s ../ geoclaw
  
install:
  - pip install -e .
  - export CLAW=${PWD}
  - export FC=gfortran
  
before_script:
  # Print CPU info for debugging purposes:
  - cat /proc/cpuinfo
  - gfortran -v
  - /usr/bin/f95 -v
  - echo "PYTHONPATH="$PYTHONPATH
  - echo "CLAW="$CLAW
  - echo "FC="$FC
  
script:
  - cd $CLAW/geoclaw
  - nosetests -sv

after_failure:
 - for failed_test_path in *_output ; do cat $failed_test_path/run_output.txt ; cat $failed_test_path/error_output.txt ; done
  
notifications:
  email: false
